# Generated by Django 5.1 on 2024-08-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_created_at_application_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
    ]
