# Generated by Django 6.1 on 2026-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countrytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='educationformtranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='educationlanguagetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='educationtypetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='specialtytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='universitytranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='countrytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='education_country_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='educationformtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='education_educationform_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='educationlanguagetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='education_educationlanguage_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='educationtypetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='education_educationtype_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='specialtytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='education_specialty_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='universitytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='education_university_translation_uniq_lang'),
        ),
    ]
