# Generated by Django 6.1 on 2026-08-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_countrytranslation_unique_together_and_more'),
        ('user', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bachelor_diploma',
            field=models.FileField(blank=True, null=True, upload_to='students/diplomas/'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.educationform'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.educationlanguage'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.educationtype'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_certificate',
            field=models.FileField(blank=True, null=True, upload_to='students/certificates/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
